# Generated by scripts/stack.sh — install via: ./scripts/install_ha_package.sh
# Phase 3: MQTT entities (broker via HA UI / configure_ha_mqtt.sh — YAML broker removed in HA 2024+)

mqtt:
  sensor:
    - name: "Solar AC Power"
      unique_id: ${INVERTER_ID}_ac_active_power
      state_topic: "${MQTT_TOPIC_PREFIX}/ac/active_power"
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
      icon: mdi:solar-power
      expire_after: ${HA_EXPIRE_AFTER}
      availability:
        topic: "${MQTT_TOPIC_PREFIX}/logger_status"
        payload_available: "online"
        payload_not_available: "offline"
      device:
        identifiers: ["deye_${INVERTER_ID}"]
        name: "${HA_INVERTER_MANUFACTURER} ${HA_INVERTER_MODEL}"
        manufacturer: "${HA_INVERTER_MANUFACTURER}"
        model: "${HA_INVERTER_MODEL}"

    - name: "Solar PV Power"
      unique_id: ${INVERTER_ID}_dc_pv1_power
      state_topic: "${MQTT_TOPIC_PREFIX}/dc/pv1/power"
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
      icon: mdi:solar-power-variant
      expire_after: ${HA_EXPIRE_AFTER}
      availability:
        topic: "${MQTT_TOPIC_PREFIX}/logger_status"
        payload_available: "online"
        payload_not_available: "offline"
      device:
        identifiers: ["deye_${INVERTER_ID}"]

    - name: "Solar Today Energy"
      unique_id: ${INVERTER_ID}_day_energy
      state_topic: "${MQTT_TOPIC_PREFIX}/day_energy"
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: total
      icon: mdi:solar-power
      expire_after: ${HA_EXPIRE_AFTER}
      availability:
        topic: "${MQTT_TOPIC_PREFIX}/logger_status"
        payload_available: "online"
        payload_not_available: "offline"
      device:
        identifiers: ["deye_${INVERTER_ID}"]

    - name: "Solar Total Energy"
      unique_id: ${INVERTER_ID}_total_energy
      state_topic: "${MQTT_TOPIC_PREFIX}/total_energy"
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: total_increasing
      icon: mdi:sigma
      expire_after: ${HA_EXPIRE_AFTER}
      availability:
        topic: "${MQTT_TOPIC_PREFIX}/logger_status"
        payload_available: "online"
        payload_not_available: "offline"
      device:
        identifiers: ["deye_${INVERTER_ID}"]

    - name: "Solar Grid Voltage"
      unique_id: ${INVERTER_ID}_ac_l1_voltage
      state_topic: "${MQTT_TOPIC_PREFIX}/ac/l1/voltage"
      unit_of_measurement: "V"
      device_class: voltage
      state_class: measurement
      icon: mdi:flash
      expire_after: ${HA_EXPIRE_AFTER}
      availability:
        topic: "${MQTT_TOPIC_PREFIX}/logger_status"
        payload_available: "online"
        payload_not_available: "offline"
      device:
        identifiers: ["deye_${INVERTER_ID}"]

    - name: "Solar Grid Frequency"
      unique_id: ${INVERTER_ID}_ac_freq
      state_topic: "${MQTT_TOPIC_PREFIX}/ac/freq"
      unit_of_measurement: "Hz"
      device_class: frequency
      state_class: measurement
      expire_after: ${HA_EXPIRE_AFTER}
      availability:
        topic: "${MQTT_TOPIC_PREFIX}/logger_status"
        payload_available: "online"
        payload_not_available: "offline"
      device:
        identifiers: ["deye_${INVERTER_ID}"]

    - name: "Solar Inverter Temperature"
      unique_id: ${INVERTER_ID}_radiator_temp
      state_topic: "${MQTT_TOPIC_PREFIX}/radiator_temp"
      unit_of_measurement: "°C"
      device_class: temperature
      state_class: measurement
      icon: mdi:thermometer
      expire_after: ${HA_EXPIRE_AFTER}
      availability:
        topic: "${MQTT_TOPIC_PREFIX}/logger_status"
        payload_available: "online"
        payload_not_available: "offline"
      device:
        identifiers: ["deye_${INVERTER_ID}"]

  binary_sensor:
    - name: "Solar MQTT Bridge Online"
      unique_id: ${INVERTER_ID}_bridge_status
      state_topic: "${MQTT_TOPIC_PREFIX}/status"
      payload_on: "online"
      payload_off: "offline"
      device_class: connectivity
      device:
        identifiers: ["deye_${INVERTER_ID}"]

    - name: "Solar Logger Online"
      unique_id: ${INVERTER_ID}_logger_status
      state_topic: "${MQTT_TOPIC_PREFIX}/logger_status"
      payload_on: "online"
      payload_off: "offline"
      device_class: connectivity
      device:
        identifiers: ["deye_${INVERTER_ID}"]
