# Generated by scripts/stack.sh — copy to <HA config>/packages/ after render.
# Configure stack.env and run: ./scripts/stack.sh render

mqtt:
  sensor:
    - name: "${HA_INVERTER_MANUFACTURER} ${HA_INVERTER_MODEL} AC Power"
      unique_id: ${INVERTER_ID}_ac_active_power
      state_topic: "${MQTT_TOPIC_PREFIX}/ac/active_power"
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
      icon: mdi:solar-power

    - name: "${HA_INVERTER_MANUFACTURER} ${HA_INVERTER_MODEL} PV1 Power"
      unique_id: ${INVERTER_ID}_dc_pv1_power
      state_topic: "${MQTT_TOPIC_PREFIX}/dc/pv1/power"
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
      icon: mdi:solar-power-variant

    - name: "${HA_INVERTER_MANUFACTURER} ${HA_INVERTER_MODEL} Today Energy"
      unique_id: ${INVERTER_ID}_day_energy
      state_topic: "${MQTT_TOPIC_PREFIX}/day_energy"
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: total
      icon: mdi:solar-power

    - name: "${HA_INVERTER_MANUFACTURER} ${HA_INVERTER_MODEL} Total Energy"
      unique_id: ${INVERTER_ID}_total_energy
      state_topic: "${MQTT_TOPIC_PREFIX}/total_energy"
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: total_increasing
      icon: mdi:sigma

    - name: "${HA_INVERTER_MANUFACTURER} ${HA_INVERTER_MODEL} Grid Voltage"
      unique_id: ${INVERTER_ID}_ac_l1_voltage
      state_topic: "${MQTT_TOPIC_PREFIX}/ac/l1/voltage"
      unit_of_measurement: "V"
      device_class: voltage
      state_class: measurement
      icon: mdi:flash

    - name: "${HA_INVERTER_MANUFACTURER} ${HA_INVERTER_MODEL} Temperature"
      unique_id: ${INVERTER_ID}_radiator_temp
      state_topic: "${MQTT_TOPIC_PREFIX}/radiator_temp"
      unit_of_measurement: "°C"
      device_class: temperature
      state_class: measurement
      icon: mdi:thermometer

  binary_sensor:
    - name: "${HA_INVERTER_MANUFACTURER} Bridge Online"
      unique_id: ${INVERTER_ID}_bridge_status
      state_topic: "${MQTT_TOPIC_PREFIX}/status"
      payload_on: "online"
      payload_off: "offline"
      device_class: connectivity

    - name: "${HA_INVERTER_MANUFACTURER} Logger Online"
      unique_id: ${INVERTER_ID}_logger_status
      state_topic: "${MQTT_TOPIC_PREFIX}/logger_status"
      payload_on: "online"
      payload_off: "offline"
      device_class: connectivity
