# Generated by scripts/stack.sh — install via: ./scripts/install_ha_package.sh
# MQTT topic suffixes from MQTT_TOPIC_PROFILE (see config/topic_profiles/)

mqtt:
  sensor:
    - name: "Solar AC Power"
      unique_id: ${INVERTER_ID}_ac_active_power
      state_topic: "${MQTT_TOPIC_PREFIX}/${MQTT_TOPIC_AC_POWER}"
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
      icon: mdi:solar-power
      expire_after: ${HA_EXPIRE_AFTER}
      availability:
        topic: "${MQTT_TOPIC_PREFIX}/${MQTT_TOPIC_DEVICE_STATUS}"
        payload_available: "online"
        payload_not_available: "offline"
      device:
        identifiers: ["solar_${INVERTER_ID}"]
        name: "${HA_INVERTER_MANUFACTURER} ${HA_INVERTER_MODEL}"
        manufacturer: "${HA_INVERTER_MANUFACTURER}"
        model: "${HA_INVERTER_MODEL}"

    - name: "Solar PV Power"
      unique_id: ${INVERTER_ID}_dc_pv1_power
      state_topic: "${MQTT_TOPIC_PREFIX}/${MQTT_TOPIC_PV_POWER}"
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
      icon: mdi:solar-power-variant
      expire_after: ${HA_EXPIRE_AFTER}
      availability:
        topic: "${MQTT_TOPIC_PREFIX}/${MQTT_TOPIC_DEVICE_STATUS}"
        payload_available: "online"
        payload_not_available: "offline"
      device:
        identifiers: ["solar_${INVERTER_ID}"]

    - name: "Solar Today Energy"
      unique_id: ${INVERTER_ID}_day_energy
      state_topic: "${MQTT_TOPIC_PREFIX}/${MQTT_TOPIC_ENERGY_TODAY}"
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: total
      icon: mdi:solar-power
      expire_after: ${HA_EXPIRE_AFTER}
      availability:
        topic: "${MQTT_TOPIC_PREFIX}/${MQTT_TOPIC_DEVICE_STATUS}"
        payload_available: "online"
        payload_not_available: "offline"
      device:
        identifiers: ["solar_${INVERTER_ID}"]

    - name: "Solar Total Energy"
      unique_id: ${INVERTER_ID}_total_energy
      state_topic: "${MQTT_TOPIC_PREFIX}/${MQTT_TOPIC_ENERGY_TOTAL}"
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: total_increasing
      icon: mdi:sigma
      expire_after: ${HA_EXPIRE_AFTER}
      availability:
        topic: "${MQTT_TOPIC_PREFIX}/${MQTT_TOPIC_DEVICE_STATUS}"
        payload_available: "online"
        payload_not_available: "offline"
      device:
        identifiers: ["solar_${INVERTER_ID}"]

    - name: "Solar Grid Voltage"
      unique_id: ${INVERTER_ID}_ac_l1_voltage
      state_topic: "${MQTT_TOPIC_PREFIX}/${MQTT_TOPIC_GRID_VOLTAGE}"
      unit_of_measurement: "V"
      device_class: voltage
      state_class: measurement
      icon: mdi:flash
      expire_after: ${HA_EXPIRE_AFTER}
      availability:
        topic: "${MQTT_TOPIC_PREFIX}/${MQTT_TOPIC_DEVICE_STATUS}"
        payload_available: "online"
        payload_not_available: "offline"
      device:
        identifiers: ["solar_${INVERTER_ID}"]

    - name: "Solar Grid Frequency"
      unique_id: ${INVERTER_ID}_ac_freq
      state_topic: "${MQTT_TOPIC_PREFIX}/${MQTT_TOPIC_GRID_FREQUENCY}"
      unit_of_measurement: "Hz"
      device_class: frequency
      state_class: measurement
      expire_after: ${HA_EXPIRE_AFTER}
      availability:
        topic: "${MQTT_TOPIC_PREFIX}/${MQTT_TOPIC_DEVICE_STATUS}"
        payload_available: "online"
        payload_not_available: "offline"
      device:
        identifiers: ["solar_${INVERTER_ID}"]

    - name: "Solar Inverter Temperature"
      unique_id: ${INVERTER_ID}_radiator_temp
      state_topic: "${MQTT_TOPIC_PREFIX}/${MQTT_TOPIC_TEMPERATURE}"
      unit_of_measurement: "°C"
      device_class: temperature
      state_class: measurement
      icon: mdi:thermometer
      expire_after: ${HA_EXPIRE_AFTER}
      availability:
        topic: "${MQTT_TOPIC_PREFIX}/${MQTT_TOPIC_DEVICE_STATUS}"
        payload_available: "online"
        payload_not_available: "offline"
      device:
        identifiers: ["solar_${INVERTER_ID}"]

  binary_sensor:
    - name: "Solar MQTT Bridge Online"
      unique_id: ${INVERTER_ID}_bridge_status
      state_topic: "${MQTT_TOPIC_PREFIX}/${MQTT_TOPIC_BRIDGE_STATUS}"
      payload_on: "online"
      payload_off: "offline"
      device_class: connectivity
      device:
        identifiers: ["solar_${INVERTER_ID}"]

    - name: "Solar Logger Online"
      unique_id: ${INVERTER_ID}_device_status
      state_topic: "${MQTT_TOPIC_PREFIX}/${MQTT_TOPIC_DEVICE_STATUS}"
      payload_on: "online"
      payload_off: "offline"
      device_class: connectivity
      device:
        identifiers: ["solar_${INVERTER_ID}"]
